regions:
  999:
    regionid: 999
    regioncode: xiaofushing
    regionname: "Xiaofushing DERP"
    nodes:
      - name: rad
        regionid: 999
        hostname: xiaofushing.duckdns.org
        stunport: 3478
        stunonly: false
        derpport: 443
        stun_test: {}